const dictionary = {
    id: {
        "nav-home": "Beranda",
        "nav-moments": "Momen",
        "nav-meet": "Tentang",
        "nav-connect": "Hubungi",
        "hero-title": "Menciptakan <em>momen bermakna</em><br>melalui koneksi yang tulus",
        "hero-desc": "Membantu audiens merasa disambut, terlibat, dan menjadi bagian dari setiap momen. Mulai dari pertemuan profesional hingga perayaan yang penuh makna.",
        "hero-btn-portfolio": "Lihat Portofolio",
        "hero-btn-connect": "Mari Berdiskusi",
        "stat-years": "Tahun",
        "stat-orgs": "Acara",
        "stat-bilingual": "Bilingual",
        "trust-label": "Telah dipercaya oleh organisasi, institusi, dan komunitas",
        "approach-title": "Lebih dari Sekadar Menjaga Jalannya Acara",
        "approach-body": "Setiap acara memiliki tujuannya sendiri. Ada yang dirancang untuk berbagi gagasan, memperkuat hubungan, atau merayakan pencapaian penting. Syaidah percaya bahwa menjadi MC bukan sekadar memandu agenda dari satu sesi ke sesi berikutnya. Peran tersebut adalah menciptakan suasana di mana pembicara merasa dihargai, tamu merasa disambut, dan percakapan mengalir secara alami. Melalui kehangatan, kepekaan terhadap situasi, dan kemampuan melibatkan audiens secara tulus, ia membantu setiap acara terasa profesional sekaligus benar-benar berkesan.",
        "moments-title": "Pengalaman Terpilih",
        "card-title-1": "Konferensi & Forum",
        "card-title-2": "Pertemuan Korporat",
        "card-title-3": "Sesi Moderasi",
        "card-title-4": "Perayaan & Pernikahan",
        "pdf-view-btn": "Lihat Portofolio Lengkap",
        "pdf-dl-btn": "Unduh PDF",
        "pdf-hint-text": "Membuka portofolio di Google Drive",
        "testi-title": "Yang Mereka Ingat",
        "testi-org-1": "Acara Pemerintah & Korporat",
        "meet-title": "Tentang Syaidah",
        "meet-body": "Nur Syaidah merupakan lulusan Ilmu Komunikasi yang telah membawakan berbagai acara sejak 2017, dari forum komunitas yang intim hingga konferensi pemerintah berskala besar. Sebagai anggota aktif Toastmasters International dan MC bilingual bersertifikat, ia memadukan struktur yang rapi dengan pembawaan yang hangat di setiap acara yang dibawakannya.",
        "manifesto-quote": "\"Acara yang paling berkesan bukanlah yang paling megah, melainkan yang membuat orang merasa <span>dilihat</span>, <span>dihargai</span>, dan <span>terhubung</span>.\"",
        "ig-title": "Momen Terkini",
        "ig-desc": "Sekilas acara terbaru, cerita di balik panggung, dan momen-momen yang berkesan.",
        "ig-cta-hint": "klik foto untuk membuka Instagram",
        "connect-title": "Sedang Merancang Sebuah Acara?",
        "connect-desc": "Mari ciptakan pengalaman yang akan diingat audiens anda.",
        "form-submit-btn": "Kirim & Buka WhatsApp →"
    },
    en: {
        "nav-home": "Home",
        "nav-moments": "Moments",
        "nav-meet": "Meet",
        "nav-connect": "Connect",
        "hero-title": "Creating <em>meaningful moments</em><br>through genuine connection",
        "hero-desc": "Helping audiences feel welcomed, engaged, and part of every moment. From professional gatherings to life's meaningful celebrations.",
        "hero-btn-portfolio": "View Portfolio",
        "hero-btn-connect": "Let's Talk",
        "stat-years": "Years",
        "stat-orgs": "Events",
        "stat-bilingual": "Bilingual",
        "trust-label": "Trusted by organizations, institutions, and communities",
        "approach-title": "More Than Keeping an Event on Schedule",
        "approach-body": "Every event has its own purpose. Some are designed to share ideas, some to strengthen relationships, and others to celebrate important milestones. Syaidah believes hosting is more than simply guiding an agenda from one session to the next. It is about creating an atmosphere where speakers feel appreciated, guests feel welcomed, and conversations flow naturally. Through warmth, attentiveness, and genuine audience engagement, she helps events feel both professional and truly memorable.",
        "moments-title": "Selected Experiences",
        "card-title-1": "Conferences & Forums",
        "card-title-2": "Corporate Gatherings",
        "card-title-3": "Moderating Sessions",
        "card-title-4": "Celebrations & Weddings",
        "pdf-view-btn": "View Full Portfolio",
        "pdf-dl-btn": "Download PDF",
        "pdf-hint-text": "Open portfolio in Google Drive",
        "testi-title": "What People Remember",
        "testi-org-1": "Government & Corporate Event",
        "meet-title": "Meet Syaidah",
        "meet-body": "Nur Syaidah holds a degree in Communication Studies and has been hosting events since 2017, from intimate community forums to large-scale government conferences. As an active member of Toastmasters International and a certified bilingual MC, she brings structure and genuine warmth to every event she hosts.",
        "manifesto-quote": "\"The most memorable events are not always the grandest, but the ones where people feel <span>seen</span>, <span>appreciated</span>, and <span>connected</span>.\"",
        "ig-title": "Latest Moments",
        "ig-desc": "A glimpse of recent events, behind-the-scenes stories, and memorable moments.",
        "ig-cta-hint": "click photo to open Instagram",
        "connect-title": "Planning an Event?",
        "connect-desc": "Let's create an experience your audience will remember.",
        "form-submit-btn": "Send & Open WhatsApp →"
    }
};